#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
PRINTS THE MAP AS THE PLAYER DISCOVERS NEW ROOMS
"""

def map1():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"          ^----D----^")

def map2():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"          ^----D----^")
    print(r"          |    c    |")
    print(r"          |    o    |")
    print(r"          D    r    D")
    print(r"          |    r    |")
    print(r"          o    i    o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")


def map3():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"o---------^----D----^")
    print(r"|         |    c    |")
    print(r"| western |    o    |")
    print(r"|  cell   D    r    D")
    print(r"|         |    r    |")
    print(r"o---------o    i    o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")

def map4():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"          ^----D----^----------o")
    print(r"          |    c    |          |")
    print(r"          |    o    |  eastern |")
    print(r"          D    r    D   cell   |")
    print(r"          |    r    |          |")
    print(r"          o    i    o----------o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")

def map5():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"o---------^----D----^----------o")
    print(r"|         |    c    |          |")
    print(r"| western |    o    |  eastern |")
    print(r"|  cell   D    r    D   cell   |")
    print(r"|         |    r    |          |")
    print(r"o---------o    i    o----------o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")

def map6():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"o---------^----D----^----------o")
    print(r"|         |    c    |          |")
    print(r"| western |    o    |  eastern |")
    print(r"|  cell   D    r    D   cell   |")
    print(r"|         |    r    |          |")
    print(r"o---------o    i    o----------o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")
    print(r"          |         |")
    print(r"          |  guard  |")
    print(r"          |  room   D")
    print(r"          |         |")
    print(r"          o----D----o")

def map7():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"o---------^----D----^----------o")
    print(r"|         |    c    |          |")
    print(r"| western |    o    |  eastern |")
    print(r"|  cell   D    r    D   cell   |")
    print(r"|         |    r    |          |")
    print(r"o---------o    i    o----------o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")
    print(r"          |         |")
    print(r"          |  guard  |----------o")
    print(r"          |  room   D darkness D")
    print(r"          |         |----------o")
    print(r"          o----D----o ")


def map8():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"o---------^----D----^----------o")
    print(r"|         |    c    |          |")
    print(r"| western |    o    |  eastern |")
    print(r"|  cell   D    r    D   cell   |")
    print(r"|         |    r    |          |")
    print(r"o---------o    i    o----------o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")
    print(r"          |         |")
    print(r"          |  guard  |")
    print(r"          |  room   D")
    print(r"          |         |")
    print(r"          o----D----o")
    print(r"          |         |")
    print(r"          |  south  | ")
    print(r"          |  room   |")
    print(r"          |         |")
    print(r"          o---------o")

def map9():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"o---------^----D----^----------o")
    print(r"|         |    c    |          |")
    print(r"| western |    o    |  eastern |")
    print(r"|  cell   D    r    D   cell   |")
    print(r"|         |    r    |          |")
    print(r"o---------o    i    o----------o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")
    print(r"          |         |")
    print(r"          |  guard  |----------o ")
    print(r"          |  room   D darkness D")
    print(r"          |         |----------o")
    print(r"          o----D----o")
    print(r"          |         |")
    print(r"          |  south  | ")
    print(r"          |  room   |")
    print(r"          |         |")
    print(r"          o---------o")

def map10():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"o---------^----D----^----------o")
    print(r"|         |    c    |          |")
    print(r"| western |    o    |  eastern |")
    print(r"|  cell   D    r    D   cell   |")
    print(r"|         |    r    |          |")
    print(r"o---------o    i    o----------o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")
    print(r"          |         |           /^^¨^¨^¨^¨^¨^¨^¨^\ ")
    print(r"          |  guard  |----------o                  \ ")
    print(r"          |  room   D darkness D       yard        D")
    print(r"          |         |----------o                  /")
    print(r"          o----D----o           \_.__.__.__._.__./")
    print(r"          |         |")
    print(r"          |  south  |")
    print(r"          |  room   |")
    print(r"          |         |")
    print(r"          o---------o")

def map11():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"o---------^----D----^----------o")
    print(r"|         |    c    |          |")
    print(r"| western |    o    |  eastern |")
    print(r"|  cell   D    r    D   cell   |")
    print(r"|         |    r    |          |")
    print(r"o---------o    i    o----------o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")
    print(r"          |         |           /^^¨^¨^¨^¨^¨^¨^¨^\ ")
    print(r"          |  guard  |----------o                  \ ")
    print(r"          |  room   D darkness D       yard        D  __FREEDOM__")
    print(r"          |         |----------o                  /")
    print(r"          o----D----o           \_.__.__.__._.__./")
    print(r"          |         |")
    print(r"          |  south  |")
    print(r"          |  room   |")
    print(r"          |         |")
    print(r"          o---------o")

def map12():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"o---------^----D----^")
    print(r"|         |    c    |")
    print(r"| western |    o    |")
    print(r"|  cell   D    r    D")
    print(r"|         |    r    |")
    print(r"o---------o    i    o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")
    print(r"          |         |")
    print(r"          |  guard  |----------o")
    print(r"          |  room   D darkness D")
    print(r"          |         |----------o")
    print(r"          o----D----o")

def map13():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"          ^----D----^----------o")
    print(r"          |    c    |          |")
    print(r"          |    o    |  eastern |")
    print(r"          D    r    D   cell   |")
    print(r"          |    r    |          |")
    print(r"          o    i    o----------o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")
    print(r"          |         |")
    print(r"          |  guard  |----------o")
    print(r"          |  room   D darkness D")
    print(r"          |         |----------o")
    print(r"          o----D----o ")
    print(r"          |         |")
    print(r"          |  south  |")
    print(r"          |  room   |")
    print(r"          |         |")
    print(r"          o---------o")

def map14():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"          ^----D----^")
    print(r"          |    c    |")
    print(r"          |    o    |")
    print(r"          D    r    D")
    print(r"          |    r    |")
    print(r"          o    i    o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")
    print(r"          |         |")
    print(r"          |  guard  |")
    print(r"          |  room   D")
    print(r"          |         |")
    print(r"          o----D----o ")


def map15():
    """Prints map"""
    print(r"           _________")
    print(r"          |         |")
    print(r"          |  your   |")
    print(r"          |  cell   |")
    print(r"          |         |")
    print(r"          ^----D----^")
    print(r"          |    c    |")
    print(r"          |    o    |")
    print(r"          D    r    D")
    print(r"          |    r    |")
    print(r"          o    i    o")
    print(r"          |    d    |")
    print(r"          |    o    |")
    print(r"          |    r    |")
    print(r"          o----D----o")
    print(r"          |         |")
    print(r"          |  guard  |----------o")
    print(r"          |  room   D darkness D")
    print(r"          |         |----------o")
    print(r"          o----D----o ")
