#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
PRINTS THE MAP AS THE PLAYER DISCOVERS NEW ROOMS
"""

def map1():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("          ^----D----^")

def map2():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("          ^----D----^")
     print("          |    c    |")
     print("          |    o    |")
     print("          D    r    D")
     print("          |    r    |")
     print("          o    i    o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")


def map3():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("o---------^----D----^")
     print("|         |    c    |")
     print("| western |    o    |")
     print("|  cell   D    r    D")
     print("|         |    r    |")
     print("o---------o    i    o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")

def map4():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("          ^----D----^----------o")
     print("          |    c    |          |")
     print("          |    o    |  eastern |")
     print("          D    r    D   cell   |")
     print("          |    r    |          |")
     print("          o    i    o----------o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")

def map5():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("o---------^----D----^----------o")
     print("|         |    c    |          |")
     print("| western |    o    |  eastern |")
     print("|  cell   D    r    D   cell   |")
     print("|         |    r    |          |")
     print("o---------o    i    o----------o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")

def map6():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("o---------^----D----^----------o")
     print("|         |    c    |          |")
     print("| western |    o    |  eastern |")
     print("|  cell   D    r    D   cell   |")
     print("|         |    r    |          |")
     print("o---------o    i    o----------o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")
     print("          |         |")
     print("          |  guard  |")
     print("          |  room   D")
     print("          |         |")
     print("          o----D----o")

def map7():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("o---------^----D----^----------o")
     print("|         |    c    |          |")
     print("| western |    o    |  eastern |")
     print("|  cell   D    r    D   cell   |")
     print("|         |    r    |          |")
     print("o---------o    i    o----------o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")
     print("          |         |")
     print("          |  guard  |----------o")
     print("          |  room   D darkness D")
     print("          |         |----------o")
     print("          o----D----o ")
 

def map8():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("o---------^----D----^----------o")
     print("|         |    c    |          |")
     print("| western |    o    |  eastern |")
     print("|  cell   D    r    D   cell   |")
     print("|         |    r    |          |")
     print("o---------o    i    o----------o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")
     print("          |         |")
     print("          |  guard  |")
     print("          |  room   D")
     print("          |         |")
     print("          o----D----o")
     print("          |         |")
     print("          |  south  | ")
     print("          |  room   |")
     print("          |         |")
     print("          o---------o")

def map9():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("o---------^----D----^----------o")
     print("|         |    c    |          |")
     print("| western |    o    |  eastern |")
     print("|  cell   D    r    D   cell   |")
     print("|         |    r    |          |")
     print("o---------o    i    o----------o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")
     print("          |         |")
     print("          |  guard  |----------o ")
     print("          |  room   D darkness D")
     print("          |         |----------o")
     print("          o----D----o")
     print("          |         |")
     print("          |  south  | ")
     print("          |  room   |")
     print("          |         |")
     print("          o---------o")

def map10():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("o---------^----D----^----------o")
     print("|         |    c    |          |")
     print("| western |    o    |  eastern |")
     print("|  cell   D    r    D   cell   |")
     print("|         |    r    |          |")
     print("o---------o    i    o----------o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")
     print("          |         |           /^^¨^¨^¨^¨^¨^¨^¨^\ ")
     print("          |  guard  |----------o                  \ ")
     print("          |  room   D darkness D       yard        D")
     print("          |         |----------o                  /")
     print("          o----D----o           \_.__.__.__._.__./")
     print("          |         |")
     print("          |  south  |")
     print("          |  room   |")
     print("          |         |")
     print("          o---------o")

def map11():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("o---------^----D----^----------o")
     print("|         |    c    |          |")
     print("| western |    o    |  eastern |")
     print("|  cell   D    r    D   cell   |")
     print("|         |    r    |          |")
     print("o---------o    i    o----------o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")
     print("          |         |           /^^¨^¨^¨^¨^¨^¨^¨^\ ")
     print("          |  guard  |----------o                  \ ")
     print("          |  room   D darkness D       yard        D  __FREEDOM__")
     print("          |         |----------o                  /")
     print("          o----D----o           \_.__.__.__._.__./")
     print("          |         |")
     print("          |  south  |")
     print("          |  room   |")
     print("          |         |")
     print("          o---------o")

def map12():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("o---------^----D----^")
     print("|         |    c    |") 
     print("| western |    o    |") 
     print("|  cell   D    r    D")
     print("|         |    r    |")
     print("o---------o    i    o")
     print("          |    d    |")
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")
     print("          |         |")
     print("          |  guard  |----------o")
     print("          |  room   D darkness D")
     print("          |         |----------o")
     print("          o----D----o")

def map13():
     print("           _________")
     print("          |         |")
     print("          |  your   |")
     print("          |  cell   |")
     print("          |         |")
     print("          ^----D----^----------o")
     print("          |    c    |          |")
     print("          |    o    |  eastern |")
     print("          D    r    D   cell   |")
     print("          |    r    |          |")   
     print("          o    i    o----------o")   
     print("          |    d    |") 
     print("          |    o    |")
     print("          |    r    |")
     print("          o----D----o")
     print("          |         |")
     print("          |  guard  |----------o")
     print("          |  room   D darkness D")
     print("          |         |----------o")
     print("          o----D----o ")
     print("          |         |")
     print("          |  south  |")
     print("          |  room   |")
     print("          |         |")
     print("          o---------o")
